services:
  app:
    image: gotodo  # 사용할 Docker 이미지를 'gotodo'라는 이름으로 설정
    build: 
      context: .    # 빌드 컨텍스트 지정
      args:
        target: dev  # 빌드 시 사용할 대상을 'dev' 단계로 지정하여 개발 모드로 빌드
    environment:
      TODO_ENV: dev
      PORT: 8090
      TODO_DB_HOST: todo-db
      TODO_DB_USER: todo
      TODO_DB_PORT: 3306
      TODO_DB_PASSWORD: todo
      TODO_DB_NAME: todo
    volumes:
      - .:/app  # 현재 디렉터리를 컨테이너 내 /app 디렉터리와 연결하여 파일 변경 시 바로 반영되도록 설정
    ports:
      - "18000:8090"
  todo-db:
    image: mysql:8.0.29
    container_name: todo-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_DATABASE: todo
    volumes:
      - todo-db-data:/var/lib/mysql
      - $PWD/_tools/ysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
volumes:
  todo-db-data: